# Generated by Django 3.2.22 on 2023-10-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_number', models.CharField(max_length=200)),
                ('Bus_type', models.CharField(max_length=200)),
                ('Total_seat', models.CharField(max_length=200)),
                ('Photo', models.CharField(max_length=200)),
                ('Engine_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Post', models.CharField(max_length=200)),
                ('Pin', models.CharField(max_length=200)),
                ('House_name', models.CharField(max_length=200)),
                ('Parent_name', models.CharField(max_length=200)),
                ('Parent_number', models.CharField(max_length=200)),
                ('Register_number', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=200)),
                ('E_mail', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='student_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=200)),
                ('BUS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.bus')),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lattitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('ALLOCATION', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student_allocation')),
            ],
        ),
        migrations.CreateModel(
            name='payment_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(max_length=200)),
                ('Fee', models.CharField(max_length=200)),
                ('Last_date', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('ALLOCATION', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student_allocation')),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('Post', models.CharField(max_length=200)),
                ('Pin', models.CharField(max_length=200)),
                ('House_name', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=200)),
                ('E_mail', models.CharField(max_length=200)),
                ('Experience', models.CharField(max_length=200)),
                ('Licence_number', models.CharField(max_length=200)),
                ('photo', models.CharField(default=0, max_length=250)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(default=1, max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=200)),
                ('Complaint', models.CharField(max_length=200)),
                ('Reply', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='DRIVER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.driver'),
        ),
    ]
