# Generated by Django 3.2.22 on 2023-10-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_driver_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.CharField(max_length=350),
        ),
    ]
