# Generated by Django 3.2.22 on 2023-10-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_driver_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_notification',
            name='STUDENT',
        ),
    ]
