# Generated by Django 3.2.22 on 2023-11-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_payment_notification_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Date',
            field=models.DateField(),
        ),
    ]
