# Generated by Django 3.2.22 on 2024-01-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_engine_number_bus_chasis_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checking_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('checkin_time', models.CharField(max_length=200)),
                ('checkout_time', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
