# Generated by Django 3.2.22 on 2024-01-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_notification',
            name='ALLOCATION',
        ),
        migrations.AddField(
            model_name='payment_notification',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
