# Generated by Django 3.2.22 on 2024-01-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20240109_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_notification',
            name='Year',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
