# Generated by Django 3.2.22 on 2024-01-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_payment_notification_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Fee',
            field=models.CharField(max_length=10),
        ),
    ]
