# Generated by Django 3.2.22 on 2024-01-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Complaint',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Reply',
            field=models.CharField(max_length=600),
        ),
    ]
