# Generated by Django 3.2.22 on 2024-01-19 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20240116_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='Lattitude',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='track',
            name='ALLOCATION',
        ),
        migrations.AddField(
            model_name='track',
            name='BUS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.bus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='Latitude',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
